name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt
          echo "prNumber=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')" >> $GITHUB_ENV
          echo "deploymentUrl=$(cat deployment-url.txt)" >> $GITHUB_ENV
  Add-Comment:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment URL to PR
        env:
          DEPLOYMENT_URL: ${{needs.Deploy-Preview.outputs.deploymentUrl}}
          PR_NUMBER: ${{needs.Deploy-Preview.outputs.prNumber}}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ env.PR_NUMBER }}
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployed at ${{env.DEPLOYMENT_URL}}"
            })
